apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pznajynq-go1 
  janus-idp.io/tekton: pznajynq-go1
  backstage.io/kubernetes-id: pznajynq-go1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pznajynq-go1
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml