apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: pznajynq-go1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pznajynq-go1 
  name: pznajynq-go1
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pznajynq-go1
    weight: 100 
