apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pznajynq-go1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pznajynq-go1 
  name: pznajynq-go1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pznajynq-go1 
